name: Dev Workflow

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet Package
        id: pack
        run: |
          dotnet pack --configuration Release --no-build
          FILE_PATH=$(ls ./bin/Release/*.nupkg)
          BASE_FILE_NAME=$(basename ${FILE_PATH})
          echo "FILE_NAME=${BASE_FILE_NAME}" >> "$GITHUB_OUTPUT"
          echo "FILE_PATH=${FILE_PATH}" >> "$GITHUB_OUTPUT"

      - name: Print File Name
        run: echo "File Name - ${{ENV.FILE_NAME}}"

      - name: Print Folder Name
        run: echo "Folder Name - ${{ENV.FILE_PATH}}"
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ${{ env.DOTNET_ROOT }}/myapp
    outputs:
      FILE_NAME: ${{ steps.pack.outputs.FILE_NAME }}
      
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg 

      - name: Print updated environment variable
        run: echo "File Name - ${{ needs.build.outputs.FILE_NAME }}"
