name: Dev Workflow

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development
  workflow_dispatch:

# used for the file name

env:
  FILE_NAME: Stahls.Api.Library

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
     
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x.x'  # According to documentation, this supports the .NET Standard 2.0 library
    
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore
    
      - name: Pack NuGet Package
        run: |
          dotnet pack --configuration Release --no-build --output ./nupkg
          FILE_PATH=$(ls ./nupkg/*.nupkg)
          FILE_NAME=$(basename ${FILE_PATH})
          scho "env.FILE_NAME=${FILE_NAME}"
          echo "${{env.DOTNET_ROOT}}"
          echo "${{env.FILE_NAME}}"
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ${{env.DOTNET_ROOT}}/myapp
