# This is a basic workflow to help you get started with Actions

name: Test-Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - development
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
   
  workflow_dispatch: # manual

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      # - name: Build with dotnet
      #   run: dotnet build --configuration Release

# Check if the build failed
  stop-on-failure:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Stop workflow
        run: echo "Stopping workflow due to build failure."

# Deployment
  
  check-github-variables:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Variable Check
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          
  # Deploy to dev
  deploy-development:
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Run a one-line script
        run: echo "Development"

  # Deploy to staging

  deploy-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Run a one-line script
        run: echo "Staging"

  # Deploy to rollback
  
  deploy-rollback:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Run a one-line script
        run: echo "Rollback"

    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
 #     - uses: actions/checkout@v4

      # Runs a single command using the runners shell
 #     - name: Run a one-line script
 #       run: sleep 5

      # Runs a set of commands using the runners shell
 #     - name: Run a multi-line script
 #       run: |
 #         echo Add other actions to build,
 #         echo test, and deploy your project.
  
  #Deployment
