name: Test-Workflow

on:
  push:
    branches:
      - development
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

  set-slot:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set Staging Slot
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          echo "Setting Staging Slot"
          echo "DEPLOYMENT_SLOT=Staging" >> $GITHUB_ENV
          echo "DEPLOYMENT_SLOT is set to Staging"

      - name: Set Rollback Slot
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Setting Rollback Slot"
          echo "DEPLOYMENT_SLOT=Rollback" >> $GITHUB_ENV
          echo "DEPLOYMENT_SLOT is set to Rollback"

      - name: Print GITHUB_ENV
        run: cat $GITHUB_ENV
        
      - name: Check if ENV_VAR is empty or null
        run: |
          if [ -z "${{ env.DEPLOYMENT_SLOTs }}" ]; then
            echo "DEPLOYMENT_SLOTs is empty or null"
            exit 1
          fi
          
      - name: Deploy
        run: echo '${{ env.DEPLOYMENT_SLOT }}'

